services:
  postgres:
    image: postgres:latest
    container_name: api_restaurants_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_restaurants_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: "npm run dev"
    container_name: api_restaurants_backend
    restart: always
    ports:
      #- '3333:3333'
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=jaIhx7GkD4OGSN-an7AlyeeP_uxi724c
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_DATABASE=api_restaurants_db
    depends_on:
      - postgres

volumes:
  pgdata:

